# Generated by Django 5.1.6 on 2025-02-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
                ('viewPassword', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Approved', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('intro', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=20)),
                ('loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
