# Generated by Django 5.1.6 on 2025-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='photo',
            field=models.ImageField(null=True, upload_to='Image'),
        ),
    ]
