# Generated by Django 5.1.6 on 2025-02-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_coder_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='Image')),
                ('username', models.CharField(max_length=20)),
                ('buyername', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('buyerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
