# Generated by Django 5.1.6 on 2025-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='role',
            field=models.CharField(default='CTO', max_length=20),
        ),
    ]
