# Generated by Django 5.1.6 on 2025-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_buyer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
