# Generated by Django 5.1.6 on 2025-02-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_buyer_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='buyername',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyerid',
            new_name='loginid',
        ),
    ]
