# Generated by Django 5.1.6 on 2025-02-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_buyername_buyer_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('companydetails', models.CharField(max_length=20)),
                ('buyerdetails', models.CharField(max_length=20)),
                ('buyerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=20)),
                ('coderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.coder')),
            ],
        ),
    ]
