# Generated by Django 5.1.6 on 2025-02-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_buyerdata_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='companydetails',
            field=models.CharField(max_length=200),
        ),
    ]
