# Generated by Django 5.1.6 on 2025-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_buyerdata_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='buyerdetails',
            field=models.CharField(max_length=200),
        ),
    ]
