# Generated by Django 5.1.6 on 2025-02-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_buyerdata_buyerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('careerlevel', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('attachment', models.ImageField(null=True, upload_to='Image')),
                ('buyerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.buyer')),
            ],
        ),
    ]
