# Generated by Django 5.1.6 on 2025-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_buyerdata_company_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(default='Published', max_length=20, null=True),
        ),
    ]
