# Generated by Django 5.1.6 on 2025-02-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(default='Actively Looking For A Freelance/Open Format UI/UX Fullstack Developer Versatile In MERN For Rectifying UI & Make UI responsive to Devices on Recently Launched Website', max_length=400),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
