# Generated by Django 5.1.6 on 2025-02-19 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_projects_description_alter_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='today',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
