# Generated by Django 5.1.6 on 2025-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_projects_today_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='today',
            field=models.DateField(),
        ),
    ]
