# Generated by Django 5.1.6 on 2025-02-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_projects_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20, null=True)),
                ('coderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.coder')),
                ('projectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projects')),
            ],
        ),
    ]
