# Generated by Django 5.1.6 on 2025-02-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_applyproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='doneby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.coder'),
        ),
        migrations.AddField(
            model_name='projects',
            name='fileupload',
            field=models.FileField(null=True, upload_to='Files'),
        ),
    ]
