# Generated by Django 5.1.6 on 2025-02-20 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_projects_doneby_projects_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='uploaddate',
            field=models.DateField(default=datetime.datetime(2025, 2, 20, 6, 31, 4, 561112, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
