# Generated by Django 5.1.6 on 2025-02-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_projects_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='fileupload',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
