# Generated by Django 5.1.6 on 2025-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_projects_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='uploaddate',
            field=models.DateField(null=True),
        ),
    ]
