# Generated by Django 5.1.6 on 2025-02-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_projects_uploaddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='fileupload',
            new_name='finalupload',
        ),
        migrations.AddField(
            model_name='projects',
            name='projectstatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='prototype',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
