# Generated by Django 5.1.6 on 2025-02-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_fileupload_projects_finalupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyproject',
            name='finalstatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
